### ISSUE TITLE
pallet-murmur: implement update wallet logic

### ISSUE THREAD

**Issue by juangirini** [ideal-lab5/idn-sdk#15]

**Comment by driemworks** [comment]
The 'update' extrinsic is basically a wrapper around the 'create' extrinsic. It is intended to allow for the data encoded on 'create' to be update. This is done by providing a zkp (a DLEQ proof) to the chain that prove you know the seed used to generate the MMR. Technically it doesn't *need* to be the seed, it's really just proving that you know some secret piece of information that the person who created the wallet also knew. Thus, this requires a new extrinsic that:
- takes in a dleq proof bytes + merkle root + proxy name + mmr size
- first verifies the dleq proof
- then update the storage entry (mapping to by proxy name) with the new root and mmr size

**Comment by driemworks** [comment]
This goes together with [#31](https://github.com/ideal-lab5/murmur/issues/31)
